### ISSUE TITLE
Upgrade to webpack4 and add prettier support.

### ISSUE THREAD

**Issue by hereisnaman** [knaxus/react-simple-starter#3]
I would like to contribute to upgrade this to webpack 4 and add prettier pre commit hooks.

**Comment by ashokdey** [comment]
Thanks @hereisnaman , glad to have a contributor onboard. 🎉 

I would love to have this change but just keep in mind it do not break any existing functionality as this kit is being used by few of the startups. 

I will add a contributing guide as well. Hope to see your PR soon ☺️
