### ISSUE TITLE
Fix the broken example app [React.js Beginners]

### ISSUE THREAD

**Issue by ashokdey** [knaxus/react-simple-starter#7]
Hello folks, it's been a long time I prepared this for my talk on Webpack. React has gone through big changes so far. What you can do here is:

- [ ] Fix the broken app that is made using this boilerplate and currently is not working

**Comment by shakti97** [comment]
Can I work on it?

**Comment by wylkon** [comment]
I can check this issue :)

**Comment by wylkon** [comment]
#10 Maybe fix with that :)

**Comment by wylkon** [comment]
Can we close this issue?

**Comment by ashokdey** [comment]
> #10 Maybe fix with that :)

yes! Thanks, @wylkon. You can go ahead and pick other issues as well.
